/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Scott VanArsdale
License: CC-BY-4.0
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/baseball_cap_3.glb');
  console.log(nodes)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group scale={0.05} position={[0, -1, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.baseballCap.geometry}
              material={materials.baseballCap}
              position={[0.005, -2.9, -11.842]}
              rotation={[-0.161, 0, 0]}
              scale={20.118}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.baseballCap001.geometry}
              material={materials.baseballCap}
              position={[0.005, -2.9, -11.842]}
              rotation={[-0.161, 0, 0]}
              scale={20.118}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.plastic.geometry}
              material={materials.plastic}
              position={[0.005, -2.9, -11.842]}
              rotation={[-0.161, 0, 0]}
              scale={20.118}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.plastic001.geometry}
              material={materials.plastic}
              position={[0.005, -2.9, -11.842]}
              rotation={[-0.161, 0, 0]}
              scale={20.118}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.baseballCap002.geometry}
              material={materials.baseballCap}
              position={[0.005, -2.9, -11.842]}
              rotation={[-0.161, 0, 0]}
              scale={20.118}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.blinn1SG.geometry}
              material={materials.blinn1SG}
              position={[0.005, -2.9, -11.842]}
              rotation={[-0.161, 0, 0]}
              scale={20.118}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.baseballCap003.geometry}
              material={materials.baseballCap}
              position={[0.005, -2.9, -11.842]}
              rotation={[-0.161, 0, 0]}
              scale={20.118}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/models/baseball_cap_3.glb');
